# Generated by Django 4.1 on 2022-09-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
    ]
