# Generated by Django 4.1 on 2022-10-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_remove_profile_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_anon_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_sales_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.profile')),
            ],
        ),
    ]
