# Generated by Django 4.1 on 2022-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_profile_commission_profile_is_anon_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
