# Generated by Django 4.1 on 2022-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_alter_promocode_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
