# Generated by Django 4.1 on 2022-11-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0008_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images.png', upload_to='profile_pics'),
        ),
    ]
