# Generated by Django 4.1 on 2022-09-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_info',
            old_name='paid_for',
            new_name='cart_number',
        ),
    ]
