# Generated by Django 4.1 on 2022-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paid_for_payment_info_cart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_info',
            name='agent_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='location',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='payment_method',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='payment_info',
            name='street',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
