# Generated by Django 4.1 on 2022-09-26 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_info_agent_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_info',
            name='agent_confirmation',
        ),
        migrations.AddField(
            model_name='payment_info',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
