# Generated by Django 4.1 on 2022-11-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_payment_info_agent_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_info',
            options={'verbose_name_plural': 'Mpesa Payments'},
        ),
    ]
