# Generated by Django 4.1 on 2022-09-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('cow products', 'for cows'), ('chicken products', 'for chicken'), ('pig products', 'for pigs'), ('general feeds', 'for any')], max_length=30),
        ),
    ]
