# Generated by Django 4.1 on 2022-09-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
