# Generated by Django 4.1 on 2022-09-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(default=True, null=True, to='Shop.cartitem'),
        ),
    ]
