# Generated by Django 4.1 on 2022-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
