# Generated by Django 4.1 on 2022-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_cart_total_price_alter_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ref_code',
            field=models.IntegerField(default=0),
        ),
    ]
