# Generated by Django 4.1 on 2022-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_cart_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(max_length=30),
        ),
    ]
