# Generated by Django 4.1 on 2022-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_cart_county_cart_location_cart_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
