# Generated by Django 4.1 on 2022-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_cart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='agent_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
