# Generated by Django 4.1 on 2022-10-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_alter_cart_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
