# Generated by Django 4.1 on 2022-10-12 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_cart_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
