# Generated by Django 4.1 on 2022-10-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_item_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='agent_code',
            field=models.CharField(default='freshi-B35L197B59', max_length=50),
        ),
    ]
