# Generated by Django 4.1 on 2022-11-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_cart_agent_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': ' customer orders'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'stock items'},
        ),
    ]
